apiVersion: v1
kind: ServiceAccount
metadata:
  name: packager
  namespace: stube
  labels:
    app: packager
    value-stream: stube
# The CI's deploy job links the gitlab-registry pull secret to this SA
# via `oc secrets link packager gitlab-registry --for=pull`.
